Avoid warnings about `function aliases/0 is unused`
```shell
user@debian:~$ mix assets.deploy
warning: function aliases/0 is unused
  mix.exs:68

Compiling 1 file (.gleam)
Compiling 1 file (.erl)
Compiling 2 files (.ex)
Generated tp_phx app
** (Mix) The task "assets.deploy" could not be found
ERROR: Service 'phoenix' failed to build : The command '/bin/sh -c mix help && mix assets.deploy' returned a non-zero code: 1
```